env:
  browser: true
  es2021: true
extends:
  - airbnb
globals:
  gtag: true
  Stimulus: true
  QRCode: true
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  import/extensions: warn
  import/no-absolute-path: warn
  import/no-unresolved: warn
  no-return-assign:
    - error
    - except-parens
