env:
  browser: true
  es2021: true
extends:
  - airbnb
globals:
  gtag: true
  Stimulus: true
  QRCode: true
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  import/extensions:
    - error
    - always
    - ignorePackages: true
  import/no-unresolved:
    - error
    - ignore:
        - 'js/.*'
  no-return-assign:
    - error
    - except-parens
