# exclude the homepage to prevent missing content errors
# exclude other wallscreens, including their local media files
exclude:
  - index.html
  - _wallscreens/we-see-you
  - _wallscreens/testing

# set this wallscreen to be the homepage so it loads immediately
defaults:
  - scope:
      path: "_wallscreens/silicon-valley/index.html"
    values:
      permalink: "/"