# Testing
name: CI

on:
  push:
    branches: [ 277-js-testing ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-202112-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-202112
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'yarn'
    - name: Install JavaScript dependencies
      run: yarn install --frozen-lockfile
    - name: Run CI
      run: bundle exec rake ci
